# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-18 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='userid',
            new_name='username',
        ),
    ]
